student_count = 25
#here are the chosen 25
puts "The students of my cohort at Makers Academy"
puts "------------------------"
puts "Dave Hole in One"
puts "Eddie the Clamberer"
puts "Catharina Rover"
puts "Igor the Melodic"
puts "Marco the Bro"
puts "Lisa Waterbaby"
puts "Michiel all ears"
puts "Jean Big Screen"
puts "Nicola Roadrunner"
puts "Jennie the Wanderer"
puts "Iona VoiceBox"
puts "Nikesh shite"
puts "Chole bendy"
puts "Toan Ice Cool"
puts "Jamie Uniball"
puts "Peter Hoy"
puts "Talal Olympian"
puts "Charlie String"
puts "Charlotte flat"
puts "Thomas Bolt"
puts "Zoe da Vinci"
puts "Hannah Climb Every Mountain"
puts "Joe Kerb Crawler"
puts "Alex Dr. Beats"
puts "Jeremy who?"
#finally, total printed
puts "Overall we have #{student_count} mighty students"